import type { Appointment, Client, Lead, Property } from './types'

export const dashboardMetrics = {
  monthlyLeads: 138,
  newClients: 24,
  activeProperties: 42,
  scheduledVisits: 18,
  conversionRate: 27,
  expectedCommission: 34000,
  commissionReceived: 17200,
  closedDeals: 12,
}

export const salesChart = [
  { month: 'Jan', revenue: 24000 },
  { month: 'Feb', revenue: 32000 },
  { month: 'Mar', revenue: 29000 },
  { month: 'Apr', revenue: 36000 },
  { month: 'May', revenue: 42000 },
  { month: 'Jun', revenue: 39000 },
]

export const pipelineSummary = [
  { stage: 'Novo Lead', total: 56, delta: '+12%' },
  { stage: 'Contato', total: 34, delta: '+8%' },
  { stage: 'Visita', total: 18, delta: '+5%' },
  { stage: 'Proposta', total: 9, delta: '+15%' },
  { stage: 'Fechado', total: 12, delta: '+22%' },
]

export const leads: Lead[] = [
  {
    id: 'L-001',
    user_id: 'U-001',
    name: 'Mariana Silva',
    phone: '(11) 99578-2321',
    whatsapp: 'Sim',
    email: 'mariana@imoveis.com',
    origin: 'Instagram',
    interest: 'Apartamento 2 dorms',
    price_range: 'R$ 850.000 - R$ 1.050.000',
    notes: 'Busca imóvel com varanda e vaga dupla.',
    status: 'Contato Feito',
    created_at: '2026-05-24',
  },
  {
    id: 'L-002',
    user_id: 'U-002',
    name: 'Carlos Souza',
    phone: '(21) 98745-6654',
    whatsapp: 'Sim',
    email: 'carlos.souza@email.com',
    origin: 'Site',
    interest: 'Casa em condomínio',
    price_range: 'R$ 1.600.000 - R$ 1.900.000',
    notes: 'Favorece condomínio com lazer e segurança 24h.',
    status: 'Visita Marcada',
    created_at: '2026-05-23',
  },
  {
    id: 'L-003',
    user_id: 'U-003',
    name: 'Fernanda Lima',
    phone: '(31) 99912-7102',
    whatsapp: 'Não',
    email: 'fernanda.lima@email.com',
    origin: 'Indicação',
    interest: 'Cobertura duplex',
    price_range: 'R$ 2.100.000 - R$ 2.500.000',
    notes: 'Quer imóvel próximo a escolas e comércio.',
    status: 'Proposta',
    created_at: '2026-05-22',
  },
  {
    id: 'L-004',
    user_id: 'U-004',
    name: 'Bruno Alves',
    phone: '(51) 91234-5567',
    whatsapp: 'Sim',
    email: 'bruno.alves@email.com',
    origin: 'WhatsApp',
    interest: 'Sala comercial',
    price_range: 'R$ 620.000 - R$ 780.000',
    notes: 'Busca investimento com fluxo elevado.',
    status: 'Novo',
    created_at: '2026-05-25',
  },
]

export const appointments: Appointment[] = [
  {
    id: 'A-001',
    user_id: 'U-001',
    lead_id: 'L-001',
    property_id: 'P-002',
    date: '2026-06-05',
    time: '10:30',
    note: 'Visita ao apartamento com varanda gourmet.',
    status: 'Confirmada',
    created_at: '2026-05-28',
    lead_name: 'Mariana Silva',
    property_title: 'Loft Premium em Higienópolis',
  },
  {
    id: 'A-002',
    user_id: 'U-002',
    lead_id: 'L-002',
    property_id: 'P-004',
    date: '2026-06-05',
    time: '14:00',
    note: 'Apresentação da casa em condomínio fechado.',
    status: 'Agendada',
    created_at: '2026-05-29',
    lead_name: 'Carlos Souza',
    property_title: 'Casa com lazer completo em Granja Viana',
  },
  {
    id: 'A-003',
    user_id: 'U-003',
    lead_id: 'L-003',
    property_id: 'P-001',
    date: '2026-06-06',
    time: '16:00',
    note: 'Negociação de proposta para cobertura duplex.',
    status: 'Agendada',
    created_at: '2026-05-30',
    lead_name: 'Fernanda Lima',
    property_title: 'Cobertura vista mar em Ipanema',
  },
]

export const properties: Property[] = [
  {
    id: 'P-001',
    user_id: 'U-001',
    title: 'Cobertura vista mar em Ipanema',
    description: 'Cobertura duplex com 4 suítes, varanda ampla e lounge gourmet.',
    type: 'Cobertura',
    price: 4200000,
    address: 'Rua das Palmeiras, 350',
    city: 'Rio de Janeiro',
    bedrooms: 4,
    bathrooms: 5,
    parking_spots: 3,
    area: 320,
    photos: ['https://images.unsplash.com/photo-1560185127-6e1b8bde3cc4?auto=format&fit=crop&w=1200&q=80'],
    status: 'Disponível',
    created_at: '2026-04-12',
  },
  {
    id: 'P-002',
    user_id: 'U-002',
    title: 'Loft Premium em Higienópolis',
    description: 'Loft com pé direito duplo e área de lazer privativa.',
    type: 'Apartamento',
    price: 1950000,
    address: 'Avenida Portugal, 210',
    city: 'São Paulo',
    bedrooms: 2,
    bathrooms: 3,
    parking_spots: 2,
    area: 142,
    photos: ['https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80'],
    status: 'Reservado',
    created_at: '2026-03-21',
  },
  {
    id: 'P-003',
    user_id: 'U-003',
    title: 'Residência contemporânea em Alphaville',
    description: 'Casa com piscina, cinema e jardim gourmet.',
    type: 'Casa',
    price: 2900000,
    address: 'Alameda das Acácias, 18',
    city: 'Barueri',
    bedrooms: 5,
    bathrooms: 6,
    parking_spots: 4,
    area: 540,
    photos: ['https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=80'],
    status: 'Disponível',
    created_at: '2026-04-30',
  },
  {
    id: 'P-004',
    user_id: 'U-004',
    title: 'Casa com lazer completo em Granja Viana',
    description: 'Condomínio com quadra, piscina e spa.',
    type: 'Casa',
    price: 1650000,
    address: 'Estrada Benedito Storani, 95',
    city: 'Cotia',
    bedrooms: 3,
    bathrooms: 4,
    parking_spots: 3,
    area: 280,
    photos: ['https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80'],
    status: 'Disponível',
    created_at: '2026-05-05',
  },
]

export const clients: Client[] = [
  {
    id: 'C-001',
    name: 'Luciana Costa',
    company: 'Costa Imóveis',
    email: 'luciana@costa.com',
    phone: '(11) 98412-3301',
    status: 'VIP',
    category: 'Comprador',
    assigned_agent: 'Ana Ribeiro',
    last_contacted: '2026-06-03',
    notes: 'Cliente de alto ticket buscando cobertura no litoral.',
  },
  {
    id: 'C-002',
    name: 'Eduardo Mello',
    company: 'Mello Invest',
    email: 'eduardo@mello.com',
    phone: '(21) 98877-4412',
    status: 'Ativo',
    category: 'Investidor',
    assigned_agent: 'Camila Souza',
    last_contacted: '2026-05-30',
    notes: 'Busca imóveis comerciais para expansão de portfólio.',
  },
  {
    id: 'C-003',
    name: 'Patrícia Faria',
    company: 'Faria Family',
    email: 'patricia@faria.com',
    phone: '(31) 99123-6621',
    status: 'Ativo',
    category: 'Proprietário',
    assigned_agent: 'Pedro Alves',
    last_contacted: '2026-05-26',
    notes: 'Interesse em casas de alto padrão na região metropolitana.',
  },
  {
    id: 'C-004',
    name: 'Gustavo Leão',
    company: 'Leão Patrimônio',
    email: 'gustavo@leao.com',
    phone: '(51) 99876-3344',
    status: 'Inativo',
    category: 'Locador',
    assigned_agent: 'Marina Nunes',
    last_contacted: '2026-05-20',
    notes: 'Reativar contato para novas demandas de locação.',
  },
]

export const proposals = [
  {
    id: 'PR-001',
    lead: 'Fernanda Lima',
    property: 'Cobertura vista mar em Ipanema',
    amount: 4100000,
    status: 'Enviada',
    due: '2026-06-12',
  },
  {
    id: 'PR-002',
    lead: 'Carlos Souza',
    property: 'Casa com lazer completo em Granja Viana',
    amount: 1650000,
    status: 'Rascunho',
    due: '2026-06-20',
  },
  {
    id: 'PR-003',
    lead: 'Mariana Silva',
    property: 'Loft Premium em Higienópolis',
    amount: 1900000,
    status: 'Aceita',
    due: '2026-05-28',
  },
]
